### ISSUE TITLE
Rename parsers to their function

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/fastatic#12]
Instead of having a genericly named `css` parser, should we name it `cssmin` as we might also get a `criticalcss` and `uncss`? The same holds for the other parsers (`htmlmin`, `imagemin`, `jsmin`).

**Comment by jpsc** [comment]
Currently we run all the parsers at the same time, changing to accommodate this, we could need to control each parser individually to be sure that we could only run `criticalcss` after `cssmin` for example.

Why don't we just keep like now, but add `criticalcss` to the css parser?
It's a more all or nothing optimization for a specific parser.

**Comment by jbmoelker** [comment]
I like the idea of having small parsers which all do one thing.
How about, when we start `criticalcss` we extend the `parser` config object:

``` javascript
parsers: {
  cssmin: {
    pattern: '**/*.css',
    parser: require('./lib/parse-cssmin')
  },
  htmlmin: {
    after: ['criticalcss'],
    pattern: '**/*.html',
    parser: require('./lib/parse-htmlmin')
  },  
  criticalcss: {
    after: ['cssmin', 'uncss'],
    pattern: '**/*.html',
    parser: require('./lib/parse-criticalcss')
  }
}
```

As an analogy Docker does this similarly in `docker-compose` using `dependsOn`.
