### ISSUE TITLE
Add progress indicator

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/fastatic#34]
The more parsers we add the longer the whole process will take. The tool may start feeling unresponsive. To change that we can add a progress indicator. Maybe something like npm's installer? Show it's busy and state what it's doing? Or more like Slack "crunching your PNG files", "squeezing the last bytes out of your CSS", "stripping the comments from your HTML" etc.

**Comment by jpsc** [comment]
Added a simple version of a spinner while parsers are working.
It's simple but it solves the unresponsive feeling. on **spinner branch**

**Comment by jpsc** [comment]
closed with #42
