### ISSUE TITLE
Deploy `dist/` to gh-pages

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/fastatic#50]
After examples are working in `dist/examples/` (#48) we can deploy `dist/` to gh-pages like we do with [voorhoede/demo-viewer](https://github.com/voorhoede/demo-viewer). This way everyone can run the optimised examples to tools like PageSpeed Insights.

Should we add some `robots.txt` or `noindex` meta somewhere so that the examples are not indexed by search engines?

Next steps could be 
- adding a `dist/index.html` which could be an (auto-generated) HTML version of the project README.
- adding a `dist/examples/index.html` which could be a list of the examples with their stats and links to the live preview. This requires us to make stats available in a different output than logged to the console.

Those steps deserve their own ticket :)

**Comment by jpsc** [comment]
closed with #55
